services:
  - type: web
    name: hirelance
    runtime: docker
    region: oregon
    plan: free
    branch: docker
    dockerfilePath: ./Dockerfile
    dockerContext: .
    envVars:
      - key: SPRING_DATASOURCE_URL
        value: jdbc:mysql://srv1999.hstgr.io/u825468745_hirelance_db
      - key: SPRING_DATASOURCE_USERNAME
        value: u825468745_hire
      - key: SPRING_DATASOURCE_PASSWORD
        sync: false
      - key: SPRING_JPA_HIBERNATE_DDL_AUTO
        value: update
      - key: SPRING_THYMELEAF_CACHE
        value: true
      - key: SPRING_JPA_SHOW_SQL
        value: false
